version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
  db:
    image: mongo:3.6.9-stretch
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: