# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    machine: 
        image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Setup Nodejs and Yarn
          command: |
            # Install Nodejs
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            source ~/.bash_profile
            nvm install v11.1.0
            nvm alias default v11.1.0

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

            # Install Yarn
            npm install -g yarn@1.9.4
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 2
      - run:
          name: Enter node.js container
          command: docker-compose exec node sh
      - run:
          name: Test
          command: |
            yarn test-ci